### ISSUE TITLE
Can we display the advanced mode when we restart the failed pipeline

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#1286]
## Description
After a pipeline failed, we need to restart it, but after click restart, it did not open advanced mode automatically.

## Describe the solution you'd like
If the failed pipeline started from advanced mode, it should open advanced mode after we clicked restart

## Has the Feature been Requested Before?
Please link any other

**Comment by e2corporation** [comment]
@warren830 I actually thought of enabling this mode by default, however we don't have a formal way of storing "advanced" mode since it's a mode-flag of the UI and not driven by any official data source setting. 

Advanced mode was intended for "multi-stage" pipelines in a way, so if you restart a multi-stage pipeline _THEN_ toggle switch to Advanced Mode -- the multi-stage configuration will be reloaded in the editor.

This will require more discussion in order to properly implement a remember setting for **Advanced Mode**.

**Comment by klesh** [comment]
I suggest that we add a field `mode` to indicate whether pipeline was created in Advanced Mode or not.
We gonna need it for #1862 anyway.
