### ISSUE TITLE
socket.io service for pipeline/task status/progress messaging

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#1406]
## Description
Right now, config-ui keep sending request to api for progress/status update. This method is old and slow.

## Describe the solution you'd like
Api should provide websocket/socket.io service for config-ui and other client to subscribe the progress/status change.

## Has the Feature been Requested Before?
No

**Comment by klesh** [comment]
@e2corporation what do you think about this proposal?

**Comment by e2corporation** [comment]
@klesh While I am in favor of SocketIO, I think this would be more useful in future iterations from now. I don't think the overhead of implementing WebSockets is worth the value at this stage since our Pipeline Progress is headed toward a "message" based indication of status rather than percentage/numeric based status which may benefit more from realtime updating. Simple REST API Polling provides adequate status activity for now.

We would also need to implement a new layer on the backend within our stack for the socketIO server/service in Go or another Language.

**Comment by klesh** [comment]
ok, lets backlog this

**Comment by e2corporation** [comment]
@klesh This Go package for implementing SocketIO on the Backend maybe useful in the future if Go will be used for this service. 

**go-socket.io** https://github.com/googollee/go-socket.io

**Comment by klesh** [comment]
Staled issue.
