### ISSUE TITLE
Jira plugin: collect the epic issue in an issue's epic link

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#1681]
## Description
Many Jira users use epic to represent 'strategy'. For example, any issue created under an epic is considered "Strategic", otherwise "Non strategic". With the epic issue, we can calculate the percentage of issues in each category: "Strategic", "Non-strategic", and "Bug fixing", so that users know the task allocation.

## Background
The current Jira plugin only collects issues by `board`. However, the epics that issues belonging to may not be collected. 
For instance, a user collected `Jira board 76` and got `issue-1`, `issue-2` and `issue3`. `Issue-1`'s epic link is issue 4 (an epic issue). As a result, issue-4 is not collected and will not appear in the `issues` table in the domain layer.

## Describe the solution you'd like
Jira plugin should also collect the epics that issues belonging to.

**Comment by klesh** [comment]
1. collect all epic issues referenced by existing issues
2. used to showing epic detail, no need to build board/epic relationship

**Comment by leglars** [comment]
@klesh @mindlesscloud  
Epic is just one of standard issue type in Jira (core). Jira installs an official plugin to provide the special ability for Epic out of box. This plugin also create some custom key within JIra and lock them. Though those key are customized, Epic has been a key feature of JIra, and we should seem those keys as original attributes of issue object.
Ideally, in my opinion, we can follow Jira's pattern, and store epic as normal issue, but add epic related keys into issue object.

**Comment by klesh** [comment]
@leglars No problem, since we had already collected `jira_issues.epic_key`, what we left to do is to collect those `epic issues` and store them into the `jira_issues` table as well,  Am I understand it correctly? @Startrekzky

**Comment by Startrekzky** [comment]
> @leglars No problem, since we had already collected `jira_issues.epic_key`, what we left to do is to collect those `epic issues` and store them into the `jira_issues` table as well, Do I understand it correctly? @Startrekzky

Correct. I guess the flow is:
1. Collect the epic issue when a Jira issue's epic_key is not empty.
2. Store the 'epic-type' issues should be stored in tables in all 3 layers: _raw_jira_api_issues, _tool_jira_issues, issues
   a. Make sure the epic issues are de-duplicated.
   b. Make sure the epic issues are enriched and converted just like other issues.

Please let me know if the flow needs to be polished. @klesh @keon94

**Comment by keon94** [comment]
@klesh is this still slotted for the v0.12.0 release?

**Comment by klesh** [comment]
Hi @keon94 , @mindlesscloud  is working on this issue already.

**Comment by klesh** [comment]
Hi @keon94,  @mindlesscloud and I had discussed this matter during Sync Up, he would like you to take over, and he will post his solution here. Would you like to keep working on it? Thanks

**Comment by mindlesscloud** [comment]
@keon94 No, you can take it, but there is one thing I would like to draw your attention to. The epic issues should not appear in the table `_tool_jira_board_issues` and `board_issues` if it does not belong to the board. Maybe we need another tool layer table to track epic issues.

> @klesh, is this being worked on? If not, I can take this one

**Comment by klesh** [comment]
cc @CamilleTeruel

**Comment by hezyin** [comment]
@keon94 Hi Keon, thanks for putting together this proposal. I'll summarize my understanding and questions below.

1. Right now we collect regular Jira issues by board. A regular Jira issue that belongs to an epic issue will have a non-empty`epic_key` field.
2. Your plan first collects regular Jira issues as before. Then a new collector gathers all non-empty `epic_key`s from _tool_jira_issues table, and call `agile/1.0/epic` with those epic keys.
3. Then a new extractor transforms raw epics to _tool_jira_issues, _tool_jira_board_issues, and etc.
4. The same old converter transforms tool layer tables to domain layer tables

 
Questions:

1. Can you elaborate a bit more on the optimization you mentioned in your point 1? Having trouble understanding that part.
2. How do we figure out which board an epic belongs to and create entries in _tool_jira_board_issues accordingly? Does `agile/1.0/epic` give out this info?
3. Where are the dupes that need to be dealt with in the new extractor coming from?

**Comment by keon94** [comment]
@hezyin 
You understood correctly, but for (3), we shouldn't need to extract the raw epics into _tool_jira_board (as mentioned by @mindlesscloud as well), because the regular issues extractor will already have extracted all the board-relevant epics to that table. This extractor should ideally only be dealing with epics that are not part of the board, but that are parents of issues that do belong to that board. Maybe we need a better name for the subtasks, like [Foreign/Indirect/Referenced,etc]EpicCollector/Extractor.

As far as your questions:

1. If we simply grab all the epics by IDs (epic-key field in_tool_jira_issues ) that's also going to return those epics that belong to the board. But these epics will already have been processed by the IssueCollector (and later IssueExtractor). We can optimize this so that we only get those that are not from the board. We should be able to run a DB Join query on _tool_jira_board_issues and _tool_jira_issues to only get the epic IDs of those issues whose epic issue-IDs are not in the _tool_jira_board_issues (issue_id key) table. This might probably be a complicated query though.

2. If we run the optimization in (1), we know we're dealing with epics that are not part of the board. My understanding from this request is that we won't be mapping these epics to the boards table. Separate pipelines involving these epics' boards will need to be run to get them on that table.

3. The collector will be getting the epics of many issues. Some issues may share the same epic. So the list of epic IDs that we get from the query might contain duplicates. We should be able to take care of this on the query itself though.

**Comment by hezyin** [comment]
@keon94 Did you mean _tool_jira_board_issues by _tool_jira_board in the following sentence?

> @hezyin You understood correctly, but for (3), we shouldn't need to extract the raw epics into _tool_jira_board (as mentioned by @mindlesscloud as well), because the regular issues extractor will already have extracted all the board-relevant epics to that table. 

Thanks for the clarification. Let me summarize my latest understanding to make sure everyone involved in the thread is on the same page.

1. If an epic issue belongs to the Jira board that we collect regular issues from, then they're already collected by the current implementation. This issue (#1681) is really about collecting (foreign) epic issues that don't belong to the Jira board themselves but are linked to regular issues from that Jira board.

2. When we collect the epic issues by going through the epic_key field in _tool_jira_issues, we can skip the ones that actually belong to the Jira board we collected. This can be checked by querying _tool_jira_board_issues.

3. The dedupe step can be done at the collector stage (when going through the epic_key field) instead of the extractor stage.

4. If foreign epic issues don't have corresponding entries in _tool_jira_board_issues, then we need to be careful when writing SQL queries for dashboards since right now many SQL queries use a board as a filter. @Startrekzky 

Please advise if there's any misunderstanding in the summary above. @klesh @Startrekzky @terrymanu @keon94

**Comment by keon94** [comment]
> @keon94 Did you mean _tool_jira_board_issues by _tool_jira_board in the following sentence?

Yes, I meant the _tool_jira_board_issues table.

**Comment by Startrekzky** [comment]
Hi @hezyin @keon94 I think we're on the same page about the epic collection and enrichment flow.

In terms of the following point, it's a design that I'm already aware of. But this won't be a problem, as the query logic will be 'boards' -> 'board_issues' -> 'issues (non-epic)' -> 'issues (epic)'. In this way, we can use boards to filter non-epic issues and get the epic that these issues belong to. As a result, we can get epic-level metrics, ie. strategic and non-strategic issue ratio.

> 4. If foreign epic issues don't have corresponding entries in _tool_jira_board_issues, then we need to be careful when writing SQL queries for dashboards since right now many SQL queries use a board as a filter. @Startrekzky
> 
> Please advise if there's any misunderstanding in the summary above. @klesh @Startrekzky @terrymanu @keon94

**Comment by Startrekzky** [comment]
Closed by #2401
