### ISSUE TITLE
[Bug] [config-ui] Jira saved without test connection

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#2112]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Jira saved without test connection.
But it tested before.

### What you expected to happen

test connection as before

### How to reproduce

Just look at: https://github.com/apache/incubator-devlake/blob/main/config-ui/src/hooks/useConnectionManager.jsx#L205

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@e2corporation Please take a look at this.

**Comment by likyh** [comment]
jenkins and jira will not test after saving but github will. It should be regard as bug.

https://github.com/apache/incubator-devlake/blob/625f8ec8fccf8b27b2d40230377fb7835ebbf637/config-ui/src/hooks/useConnectionManager.jsx#L281-L287

**Comment by e2corporation** [comment]
No this was not a bug, the only reason this was done was so that token & multi-token providers, mainly GitHub (jira and gitlab also used token field at that point) could be notified of a bad token upon entering. Github now uses a different PAT Token system that does inline-testing when the token changes, testing during save no longer needs to be done for any provider, this ticket is being closed.
