### ISSUE TITLE
[Feature][Config UI] Showing a sense of progress when the blueprint is running

### ISSUE THREAD

**Issue by yumengwang03** [apache/incubator-devlake#2249]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We want to give users a sense of progress and reduce their anxiety while the pipeline is running.

On the Blueprint detail page, for a historical run/pipeline that is running, there should be:
- Stages
- Tasks
- Number of substasks/total number of subtasks
- Number of completed records of each subtask

### Related issues

https://github.com/apache/incubator-devlake/issues/1862
https://github.com/apache/incubator-devlake/issues/822
https://github.com/apache/incubator-devlake/issues/2197

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@yumengwang03 This is "NO-CAN-DO". In order to support **Estimated Time**, we need **Percentage Progress**, to be more accurate, we need an ACCURATE PERCENTAGE PROGRESS based on time (calculated by `finishedSubasks/totalSubtasks` is NOT time-based). And, since the data is coming from outside, most likely via some API services. No, this is NO NO NO.
Please close this issue, and shake it out of your head, so we can still be friends.

**Comment by yumengwang03** [comment]
> Contributor

We talked about this yesterday. This issue is more about if a subtask takes a really long time to complete, users may think it's stuck. So we need to show how many records has been run, etc.

Btw, this is part of the design for the new config UI's blueprint detail page.

**Comment by yumengwang03** [comment]
Closing this cause it's a dup from https://github.com/apache/incubator-devlake/issues/2197

**Comment by yumengwang03** [comment]
See design here: https://www.figma.com/file/Eux4Dhorxp7M0TwzOnL6Yh/Config-UI-for-V1.0?node-id=817%3A10164

**Comment by abeizn** [comment]
sloved
