### ISSUE TITLE
[Feature][Docs] Usage of GitHub Project Boards in Roadmap

### ISSUE THREAD

**Issue by krshkodes** [apache/incubator-devlake#2387]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

GitHub project boards can help us maintain a list of tasks, and roadmap here in GitHub itself, which can be then linked to the Roadmap section in the readme, for a more dynamic, updated and better.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by warren830** [comment]
@krshkodes  Thank you for your suggestion! But I did not find a way to create a project inside an apache repo. And could you please give us more info and what we can gain from the project boards?

**Comment by krshkodes** [comment]
Hi @warren830, This is the official docs for project boards: https://docs.github.com/en/issues/trying-out-the-new-projects-experience/about-projects

Project boards have multiple benefits:
- Roadmap and Tracking of tasks
- Conversion of roadmap features into issues, finally sub-issues
- Easier management for the roadmap and bug submissions
- A `projects` tab where everyone can view the board
- It is like trello but on github
- A more dynamic roadmap section to our readme

**Comment by klesh** [comment]
Oh, we tried that before, not very useful. We have to go back and forth between `issues` and `projects` for management. For example, in order to create an issue for a project board, one has to create an issue on `issues` page first, then add it to the project, then switch to project boards, and **SEARCH** the one just created, not really enjoyable IMO.
We would love to try it if the Github Project Boards can offer the UX as trello

**Comment by klesh** [comment]
alright, it was approved. https://github.community/t/github-action-badge-always-show-failing/259290
