### ISSUE TITLE
[Bug] Docker Container keep restarting. 

### ISSUE THREAD

**Issue by shubham-cmyk** [apache/incubator-devlake#2454]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Docker container keep restarting. 
👀  Ubuntu Local host 
![image](https://user-images.githubusercontent.com/69793468/178051542-703c1551-96ef-46ec-8352-f26a8217b0f1.png)

👀  AWS 
<img width="949" alt="image (5)" src="https://user-images.githubusercontent.com/69793468/178051810-b2dfb461-58d8-4178-8c57-6e321909d07e.png">

### What you expected to happen

👀  Docker Container logs 
<img width="960" alt="image (6)" src="https://user-images.githubusercontent.com/69793468/178052237-a3f270c1-0728-4268-bb8a-58eb504e686a.png">

Container are not starting up in proper order. 

### How to reproduce

Release Version : 0.10.1

Follow up the general installation method as stated in Readme 

### Anything else

We are using v3 docker-compose which has removed ability of container for wait for eachother. 

### Version

v0.10.1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by keon94** [comment]
The ordering is technically fine (depends_on field in the compose file manages the ordering). The problem is, each container has a bootstrap process that takes some time to complete (e.g. mysql), so just because it has started it doesn't mean it's ready. In this case devlake is trying to talk to mysql before it is fully ready, and that throws an error.

With docker-compose v2 one would define healthchecks in the compose file and have the containers wait using conditions until their dependencies are healthy before boostrapping. v3 removed this feature as far as I am aware.

So our options are:
1. Use the v2 docker-compose spec, and use healthchecks and conditions in the compose file
2. Enhance the devlake service logic to retry DB connectivity for a while
3. Apparently the more recent compose versions allow backwards portability as far as support for conditions go [see this discussion](https://github.com/peter-evans/docker-compose-healthcheck/issues/3). Maybe investigate this and see if it'll work.
