### ISSUE TITLE
how to config github, how to the the input

### ISSUE THREAD

**Issue by matthewxuda** [apache/incubator-devlake#2469]
how to config github, how to get token

![image](https://user-images.githubusercontent.com/5927005/178401742-1f12a5bb-7d4d-44b4-bf8f-750bd6476747.png)

**Comment by likyh** [comment]
You can use the default value in options.
Token can get in github setting.
More info at: https://devlake.apache.org/docs/Plugins/github

**Comment by e2corporation** [comment]
@matthewxuda Your **Auth Token** (Personal Access Token / PAT) must be created by you first at GitHub.com, please see GitHub docs on creating _Personal Access Tokens_ here: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token. Once created, copy the value and paste it into the auth token field.

Additionally, your **Endpoint URL** value appears to be incorrect, this is GitHub API's Endpoint, not the value of a git-project repository url. Endpoint URL for your GitHub Connection Instance should be set to: **https://api.github.com/**

**Comment by matthewxuda** [comment]
![image](https://user-images.githubusercontent.com/5927005/184468528-a4fb8157-77c8-4396-a96c-96ff0d5ec7cb.png)

**Comment by Startrekzky** [comment]
Hi @matthewxuda , the configuration rules are listed below:

### Issue Tracking
Severity: Parse the value of severity from issue labels.

- when your issue labels for severity level are like 'severity/p0', 'severity/p1', 'severity/p2', then input 'severity/(.*)$'
- when your issue labels for severity level are like 'p0', 'p1', 'p2', then input '(p0|p1|p2)$'
- Component: Same as "Severity".

### Priority: Same as "Severity".

- Type/Requirement: The type of issues with labels that match given regular expression will be set to "REQUIREMENT". Unlike "PR.type", submatch does nothing, because for issue management analysis, users tend to focus on 3 kinds of types (Requirement/Bug/Incident), however, the concrete naming varies from repo to repo, time to time, so we decided to standardize them to help analysts metrics.

- Type/Bug: Same as "Type/Requirement", with type setting to "BUG".

- Type/Incident: Same as "Type/Requirement", with type setting to "INCIDENT".

### Code Review
Type: The type of pull requests will be parsed from PR labels by given regular expression. For example:

- when your labels for PR types are like 'type/feature-development', 'type/bug-fixing' and 'type/docs', please input 'type/(.*)$'
- when your labels for PR types are like 'feature-development', 'bug-fixing' and 'docs', please input '(feature-development|bug-fixing|docs)$'
- Component: The component of pull requests will be parsed from PR labels by given regular expression.

### Additional Settings (Optional)
- Tags Limit: It'll compare the last N pairs of tags to get the "commit diff', "issue diff" between tags. N defaults to 10.

- commit diff: new commits for a tag relative to the previous one
issue diff: issues solved by the new commits for a tag relative to the previous one
- Tags Pattern: Only tags that meet given regular expression will be counted.

- Tags Order: Only "reverse semver" order is supported for now.

Please click Save to save the transformation rules for the repo. In the data scope list, click Next Step to continue configuring.

------------------------------------------------------------------

Please read this [doc](https://devlake.apache.org/docs/UserManuals/ConfigUI/GitHub#step-3---adding-transformation-rules-optional) for more details.
