### ISSUE TITLE
[Bug][Config UI] Uncaught (in promise) TypeError: ri[n.plugin.toLowerCase(...)] is not a function

### ISSUE THREAD

**Issue by long2ice** [apache/incubator-devlake#2549]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I click blueprints detail, the error occured and display white screen

<img width="1375" alt="image" src="https://user-images.githubusercontent.com/13377178/179907610-386b2cc9-ab04-4d5c-8561-1e36a063226c.png">

### What you expected to happen

Show detail rightly

### How to reproduce

Create blueprint and run it, then click show detail icon

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
@long2ice Thank you for reporting this issue, the `StageTaskName.jsx` child component needs a property exists check `plugin?.toLowerCase()` it seems the `plugin` key is missing either due to data inconsistency of what was expected, or this key may sometimes be missing with a blueprint's detail. 

I'll add a patch on a current PR in development to see if that resolves the issue.

**Comment by long2ice** [comment]
How about this?

**Comment by Startrekzky** [comment]
> How about this?

What do you mean by "this"?

**Comment by long2ice** [comment]
Sorry, I mean when this issue can be resolve?

**Comment by klesh** [comment]
Sorry, which icon?

**Comment by klesh** [comment]
Not a blocker, will be fixed on next Milestone
