### ISSUE TITLE
[Bug][config-ui] Blueprint online status not updating

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#2571]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

init state:
![image](https://user-images.githubusercontent.com/61080/180210512-8fbeca20-ef58-4c36-abe6-c638e077b0bb.png)

update token:
![image](https://user-images.githubusercontent.com/61080/180210438-860d0f78-e173-48a3-9e83-6d5c6265533f.png)

saved successfuly:
![image](https://user-images.githubusercontent.com/61080/180210512-8fbeca20-ef58-4c36-abe6-c638e077b0bb.png)

### What you expected to happen

Github should be online

### How to reproduce

1. make connection "offline"
2. create a new blueprint
3. select that connection, update the credential and make sure it passed the test successfully
4. click Save Connection
5. see error

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
@klesh It looks like the testing logic you added recently for this connections list will need to be re-executed on a connection list change.

**Comment by e2corporation** [comment]
@klesh Did you check your console to verify the BE Test response didn't yield a 400 response? If be does not return a valid test response due to DNS failure the status will be stuck in offline.

<img width="1619" alt="Screen Shot 2022-07-21 at 11 44 43 AM" src="https://user-images.githubusercontent.com/1742233/180256821-92903c30-b3ed-41ce-97fd-c0ffd1e72238.png">
