### ISSUE TITLE
[Bug][backend-framework] duplicate name when adding connection should have right message

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#2892]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/3294100/187595920-e4e9dbad-b371-4a06-8732-dab7b27bb109.png)

### What you expected to happen

tell me the name duplicate.

### How to reproduce

just try to create a connection that has a name equal to the existing connection.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
This is a backend issue when a user tries to add a connection with the same name, instead of returning with an error the backend is returning with the Existing connection response and a success flag. UI will never raise an error, and user is redirected back to Integrations page because UI thinks (as it should) the interaction was successful, saveComplete gets populated with a valid connection payload.

BE needs to return with an error response like it previously did.

**Comment by likyh** [comment]
> @likyh当用户尝试添加具有相同名称的连接时，这是一个后端问题，而不是返回错误，后端返回的是现有连接响应和成功标志。UI 永远不会引发错误，并且用户被重定向回集成页面，因为 UI 认为（应该）交互成功，saveComplete 会填充有效的连接有效负载。
> 
> BE 需要像以前一样返回错误响应。现在发生的情况是，现有的同名连接正在被覆盖`[POST]`

So I mark the module as `core`.

**Comment by likyh** [comment]
Only occur when pg
