### ISSUE TITLE
[Bug][config] jira transfomation will affact other jira's transfomation when adding blueprint

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#2906]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

If I create 2 Jira when adding blueprint:
![image](https://user-images.githubusercontent.com/3294100/187821297-c921e67e-7b2b-4455-b075-d750cc28bad5.png)
![image](https://user-images.githubusercontent.com/3294100/187821267-85f1036a-57a6-4b1b-b4af-8d52fd76c48e.png)
And edit the transformation rule in one of them:
![image](https://user-images.githubusercontent.com/3294100/187821592-4dbc2482-4889-47b7-add4-6fbb0ef863ce.png)

But I find another also has been edited.
![image](https://user-images.githubusercontent.com/3294100/187821828-3842a718-0f17-4002-87fa-21f7bf3fb8af.png)

### What you expected to happen

can edit separately.

### How to reproduce

the same as "What happened"

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
This appears to be happening because 'test_board' happens in both connections, even though the boards list structure is key'd by connection index. This issue has not been found during prior QA testing, will troubleshoot and resolve.

**Comment by e2corporation** [comment]
@likyh Are connections "j2221" and "1111" sharing the same jira credentials & endpoint? One of the assumptions is that project IDs and board IDs are unique, regardless of connection. I will still make adjustments for this scenario, but I think you duplicating the _same_ jira connection source as 2 separate jira instances is the main reason you have "test_board" configuration duplicated because they share the same board ID #.
