### ISSUE TITLE
[Bug][config-ui] Click 'Add Transformation' for a github connection, the cursor went to the wrong input

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#3243]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![6ES75wbojD](https://user-images.githubusercontent.com/14050754/192831509-05aa5b62-23e4-4ebe-ad2d-b6fca36a303d.jpg)
![olTd8GQ5wV](https://user-images.githubusercontent.com/14050754/192831642-689181a3-bce3-4f3d-beb2-f07567f01c93.jpg)

### What you expected to happen

The cursor should stick to the top of the transformation page.

### How to reproduce

1. create a blueprint and select a github connection
2. click 'Add Transformation'

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e2corporation** [comment]
There may not be explicit `TabIndex` attributes set for the inputs to dictate which input can get focused first, so this textarea maybe the unintended default of what's being focused.

**Comment by e2corporation** [comment]
@likyh @mintsweet If one of you is interested in resolving this, the easiest path would be to patch all the `settings/[provider].jsx` transformation partials so that the `tabIndex` attribute is specified for all _applicable_ form controls starting at the top with `tabIndex={0}` then `tabIndex={1}` etc. Alternatively a `ref` could be used on just the first input on each corresponding transformation setting file, and then focus could be enforced programmatically with JS, but this route may incur more code changes.

I think Option 1 with applying `tabIndex` property would be the safe route to go.

**Comment by e2corporation** [comment]
The other thing if note is that _Deployment_ transformation settings are shared too, and _conditional_ so those inputs should also receive `tabIndex` props. Create a Blueprint with ALL Data Entities selected so all transformation settings are in view, and then assign the Tab Indexes based on that render in terms of ordering.

**Comment by mintsweet** [comment]
I will fix this.

**Comment by Startrekzky** [comment]
Verified.
