### ISSUE TITLE
[Feature][jenkins] Jenkins uses `job` as the `scope`

### ISSUE THREAD

**Issue by klesh** [apache/incubator-devlake#3296]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

For a long long time, we accepted the fact that Jenkins doesn't have scopes, this creates many if not countless problems in terms of System and UI design...

In a recent discussion, we realized that the `job` inside `Jenkins` could be perceived as data scopes.

### Use case

1. This is required for project related metric like dora
2. config-ui could be more unified

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
The same as: https://github.com/apache/incubator-devlake/issues/3264

**Comment by klesh** [comment]
LGTM

**Comment by likyh** [comment]
The prev PR does not support the path in Jenkins job selector.
 
![image](https://user-images.githubusercontent.com/3294100/199252226-8b1b984a-095b-4bf2-90d8-a05a87b6cef0.png)

Because our frontend UI lib [Blueprint](https://blueprintjs.com/docs/versions/3/#select/select-component) not support cascader like this:
![image](https://user-images.githubusercontent.com/3294100/199253115-8f45b517-7b35-49ea-b209-79629210e82e.png)


So I plan show patt like this:
![image](https://user-images.githubusercontent.com/3294100/199256563-09ece0ef-15c7-400a-90e9-2dc5b5fb1bfe.png)

If path click:

![image](https://user-images.githubusercontent.com/3294100/199257193-92c62cdd-16bd-4ba2-81fa-d02ac3072c8a.png)

**Comment by yumengwang03** [comment]
This feature depends on this: https://github.com/apache/incubator-devlake/issues/3670
