### ISSUE TITLE
[Refactor][config-ui] merge board and project in create-blueprint.jsx

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#3329]
## What and why to refactor
https://github.com/apache/incubator-devlake/blob/7b0199a6d8557d4f18b73200d619a96d10df0163/config-ui/src/components/blueprints/create-workflow/DataTransformations.jsx#L66-L73

board and project have the same logic, and the same usage. So we need to merge them into one var.
Similarly, I can deal with `configuredProject` and `configuredBoard`, `activeProject` and `activeBoard` in the same way.

## Describe the solution you'd like
merge board and project into `connectionScope`

**Comment by e2corporation** [comment]
@likyh The Active/Configured Board and Project Entity state vars should be consolidated to either a) `[configuredRecord, setConfiguredRecord]` or b) `[configuredEntity, setConfiguredEntity]` or c) Some naming group better than `a)` or `b)`

By design it's state would be an Instance of any one of the following Data Models that represents a "Board" or "Project" or "Job" or some other future Entity to be treated as the main scope entity.

- `GitlabProject`
- `GitHubProject`
- `JiraBoard`
- `JenkinsJob`
- `BitbucketProject` (_Future example_ )
- `AzureJob`  (_Future example_ )
- `....`

**Entity ID** can easily be obtained by the Model's Accessory method (`gitlabProject.getEntityId()`), since all models will have the base traits required for these model instances.
```
gitlabProject.getEntityId()   // "91837121231"
```
```
githubProject.getEntityId() // "merico-dev/lake"
```

**Variant** can be used to control business and logic flow based on the varying concept types so UI features can tailored to the differing project concepts.
```
gitlabProject.get('variant')   // "project"
gitlabProject.variant // "project"
```
```
jiraBoard.get('variant')   // "board"
jiraBoard.variant // "board"
```
```
jenkinsJob.get('variant')   // "job"
jenkinsJob.variant // "job"
```
