### ISSUE TITLE
[Refactor][config-ui] try to delete set function in deps.

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#3334]
## What and why to refactor
https://github.com/apache/incubator-devlake/blob/7b0199a6d8557d4f18b73200d619a96d10df0163/config-ui/src/pages/blueprints/create-blueprint.jsx#L501-L505
delete set function in deps.

We normally won't add the set functions in deps except in some specific situations. Deleting them will not trigger the linter's warning.

An example:
In one file:
```js
  const [a, setA] = useState(..)
  const updateColumnInA = useCallback(
    (key, value) => (setA[key] = value),
    [setA]
  )
```
In another file：
```
const [b, setB] = useState(..)
useEffect(() => {
updateColumnInA('xxxxx', b)
}, [b, updateColumnInA])
```

In the above codes, because of the existence of setA, the changes of `a` will trigger the changes of `b`. It is not necessary and sometimes it will lead to an endless loop.

## Describe the solution you'd like
check all deps and try to delete set functions unless they are necessary.

**Comment by e2corporation** [comment]
@likyh The goal should be to embrace proper usage of Effects and understand dependency management, not move all properties as callback arguments so as to _avoid_ the linter warnigs? Just having a setter as a dependency is not the problem that causes endless loop.

**Comment by likyh** [comment]
@e2corporation Please read the issue again. That is the solution for some endless loop situations. Not for linter waring.

**Comment by e2corporation** [comment]
@likyh We don't have any loops to worry about last time I checked, except for a recent PR by Junren on DataTransformations which is the only warning on the lint log currently.

**Comment by likyh** [comment]
@e2corporation I describe a scenario that may lead to an endless loop, rather than saying that there is an endless loop now. In fact, the problem also exists. I remember seeing in the object that you annotated the original simple scheme and used a complex scheme to avoid an endless loop.

In any case, this is a potential problem. It should not be said that if there is no problem, it will not be solved.

**Comment by e2corporation** [comment]
@likyh I think a majority of the problem here is your interpretation of how Effects should work. There are times when a func will have callback args, and other times where a Setter is not needed as a dependency but that depends on the _context_ of how the effect is being used and how the developer is implementing the flow. 

If you encounter a loop problem going forward, you simply troubleshoot it and fix related dependencies to resolve the issue. If adding a required dependency causes loop, then look closer at the dependency itself whether it's a setter func or some other generic constant that simply needs a callback wrap to solve the problem.

The comment about using a an Object prop rather than the whole object is well documented by react, and also by the article I shared. I mentioned that to give you a better understanding of nuances when using Objects as a dependency. In some cases we want the whole object, in other cases we only need a single prop like `Object?.id`.

**Comment by e2corporation** [comment]
@likyh I'm not saying that you can't optimize an Effect or fix a potential issue you have strongly identified, but the task of "delete all set functions in deps" seems a bit of a generalization. Are you trying to do this to the entire codebase or just this one `handleTransformationCancel` method ?

If you are just refactoring `handleTransformationCancel` then go for it, If you are trying to impose this observation of no-setters in deps on all files that's a different issue.
