### ISSUE TITLE
[Feature][Bitbucket] add Bitbucket Issue Tracking transformationRules

### ISSUE THREAD

**Issue by thenicetgp** [apache/incubator-devlake#3368]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
@hezyin @thenicetgp @yumengwang03 Compared to GitHub's transformation rules

1. BitBucket does not have `priority`, `component` because the BitBucket issue has `priority`, `component` as semantically explicit attributes that do not need to be extracted from the issue labels like GitHub does.

2. BitBucket does not have a `type` configuration because 
   a. BitBucket issue also has a `type` field, so there is no need to extract it from labels like GitHub does.
   b. BitBucket types are only "enhancement", "proposal", "task", "bug", and cannot be customized by users. So by default we transform "enhancement", "proposal" and "task" to REQUIREMENT and "bug" to BUG to save users' time.

3. BitBucket does not have `severity` because BitBucket does not have related fields, so let's put it aside for a while and do it later.

4. BitBucket has "status mapping" because unlike GitHub issues which only have 2 statuses "open" and "closed", BitBucket has a lot more. We can't transform them to the 3 standard issue statuses "TODO", "IN_PROGRESS" and "DONE" on behalf of users. Thus, we add the "status mapping" configuration to let users decide.

**Comment by thenicetgp** [comment]
@Startrekzky @hezyin @yumengwang03 BitBucket add a new Status mapping rule `issueStatusOther` in order to let users decide some status they do not want to decide.
