### ISSUE TITLE
[Bug][jira] Different behaviour of issue type mapping in v0.12 and v0.14

### ISSUE THREAD

**Issue by narrowizard** [apache/incubator-devlake#3441]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

In devlake v0.12, jira issue's type mapping is based on issue type's untranslatedName field. But in devlake v0.14 it is based on issue type's name field.

### What you expected to happen

Expected consistent behaviour in two version.

### How to reproduce

Sync jira data with same transformation rules in v0.12 and v0.14. 
Should prepare some issue type of different language, and set personal language to something different than english.

### Version

v0.12.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by narrowizard** [comment]
Closed by #3442

**Comment by likyh** [comment]
The first issue about this serial issues is that @hezyin found transformation in jira not works.
I find it is caused by transformation using id as key in the frontend and name in the backend. So https://github.com/apache/incubator-devlake/pull/3202 merged.

But it make a mismatch of the transformation mode between 0.12 and 0.14. After discussion, https://github.com/apache/incubator-devlake/pull/3258 on main change the key in the transformation to name again. And we decide not use the translated name because it does not work as we expect.

And this issue and #3442 drop translated name for 0.14.
