### ISSUE TITLE
[Bug][pipeline] pipeline cannot work after migration failed

### ISSUE THREAD

**Issue by narrowizard** [apache/incubator-devlake#3537]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I upgrade devlake from v0.12 to v0.14 version, devlake reports an migration error.  
After that, all pipelines failed immediately after creating.  

### What you expected to happen

Pipelines should work properly.

### How to reproduce

Not sure what causes the migration failed.

### Anything else

```migration log
message:{"log":"panic: runtime error: invalid memory address or nil pointer dereference\n","stream":"stderr","time":"2022-10-20T07:03:34.748952321Z"}	devlake:/var/log/containers/devlake-6f6588bd5c-vtfjw_default_devlake-20fdf992368ce89ea37638980540c6a18c77107206e556d854fa13bda451d52a.log	t:07:03:35.+0000
message:{"log":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1722767]\n","stream":"stderr","time":"2022-10-20T07:03:34.748968778Z"}	devlake:/var/log/containers/devlake-6f6588bd5c-vtfjw_default_devlake-20fdf992368ce89ea37638980540c6a18c77107206e556d854fa13bda451d52a.log	t:07:03:35.+0000
message:{"log":"\n","stream":"stderr","time":"2022-10-20T07:03:34.748974233Z"}	devlake:/var/log/containers/devlake-6f6588bd5c-vtfjw_default_devlake-20fdf992368ce89ea37638980540c6a18c77107206e556d854fa13bda451d52a.log	t:07:03:35.+0000
message:{"log":"goroutine 1519 [running]:\n","stream":"stderr","time":"2022-10-20T07:03:34.748978045Z"}	devlake:/var/log/containers/devlake-6f6588bd5c-vtfjw_default_devlake-20fdf992368ce89ea37638980540c6a18c77107206e556d854fa13bda451d52a.log	t:07:03:35.+0000
message:{"log":"github.com/apache/incubator-devlake/services.runPipeline(0x12b?)\n","stream":"stderr","time":"2022-10-20T07:03:34.748981173Z"}	devlake:/var/log/containers/devlake-6f6588bd5c-vtfjw_default_devlake-20fdf992368ce89ea37638980540c6a18c77107206e556d854fa13bda451d52a.log	t:07:03:35.+0000
message:{"log":"\u0009/app/services/pipeline_runner.go:125 +0x227\n","stream":"stderr","time":"2022-10-20T07:03:34.748984662Z"}	devlake:/var/log/containers/devlake-6f6588bd5c-vtfjw_default_devlake-20fdf992368ce89ea37638980540c6a18c77107206e556d854fa13bda451d52a.log	t:07:03:35.+0000
message:{"log":"github.com/apache/incubator-devlake/services.RunPipelineInQueue.func1()\n","stream":"stderr","time":"2022-10-20T07:03:34.748997216Z"}	devlake:/var/log/containers/devlake-6f6588bd5c-vtfjw_default_devlake-20fdf992368ce89ea37638980540c6a18c77107206e556d854fa13bda451d52a.log	t:07:03:35.+0000
message:{"log":"\u0009/app/services/pipeline.go:184 +0xff\n","stream":"stderr","time":"2022-10-20T07:03:34.749001106Z"}	devlake:/var/log/containers/devlake-6f6588bd5c-vtfjw_default_devlake-20fdf992368ce89ea37638980540c6a18c77107206e556d854fa13bda451d52a.log	t:07:03:35.+0000
message:{"log":"created by github.com/apache/incubator-devlake/services.RunPipelineInQueue\n","stream":"stderr","time":"2022-10-20T07:03:34.74900409Z"}	devlake:/var/log/containers/devlake-6f6588bd5c-vtfjw_default_devlake-20fdf992368ce89ea37638980540c6a18c77107206e556d854fa13bda451d52a.log	t:07:03:35.+0000
message:{"log":"\u0009/app/services/pipeline.go:181 +0x5c\n","stream":"stderr","time":"2022-10-20T07:03:34.749007356Z"}	devlake:/var/log/containers/devlake-6f6588bd5c-vtfjw_default_devlake-20fdf992368ce89ea37638980540c6a18c77107206e556d854fa13bda451d52a.log	t:07:03:35.+0000
```

### pipeline log
![f18eec08-927f-4a21-ba0d-2ecb6661877c](https://user-images.githubusercontent.com/11383928/197141249-e3af34bd-8479-4023-82a7-a68fac424dd6.jpeg)

![image](https://user-images.githubusercontent.com/11383928/197141443-f8a136fb-7151-401e-9ee5-a86e25598a4b.png)

![d21622b5-a268-4bea-8285-cb04b11fc080](https://user-images.githubusercontent.com/11383928/197141502-dc4ddbf8-7f23-4171-8221-2e7402f1743a.jpeg)

### Version

v0.14.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Related to https://github.com/apache/incubator-devlake/issues/3508

Due to migration failure, the maximum id of the `pipelines` table is smaller than expected, however, the `tasks` table migrated successfully, so it contained more `pipeline_id` than `pipelines` table.
When creating new pipelines, the `pipeline_id` in `tasks` table collides which causes the pipeline having more `tasks` than expected, in this case, https://github.com/apache/incubator-devlake/blob/release-v0.14/runner/run_pipeline.go#L54 triggered, return without setting the `beganAt` for the `pipeline` which leads to the final error.

As you can tell, it is tedious to track down and explain what was wrong. It would be much better to put `beganAt` and `spentSeconds` for robustness so we can see what was wrong right away. However, it was designed this way because of `temporal mode`(related to `beganAt`) and `panicking catch`(must be dealt with in a caller function). 

I need more time to come out a better solution.

**Comment by Startrekzky** [comment]
@klesh Any updates about the issue?

**Comment by klesh** [comment]
> @klesh Any updates about the issue?

No, no really. It failed because there were multiple devlake containers while upgrading, there are 2 way to prevent this:

1. Manual: Users to make sure old containers are down before upgrade devlake (need to update document)
2. Automated: We find a way to prevent multiple devlake instances from accessing the same database (not easy)

**Comment by klesh** [comment]
No viable mechanism can prevent this problem from happening at this point.
I suggest that we make sure the `devlake` container was killed before bringing up the newer version until we find a solution.

**Comment by klesh** [comment]
related to #3466
