### ISSUE TITLE
[Bug][DORA Dashboard] Metrics don't honor time-range

### ISSUE THREAD

**Issue by keon94** [apache/incubator-devlake#3662]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Looks like the dashboard is insensitive to time-ranges and pulls data from the last 6 months regardless of what the user sets.

### What do you expect to happen

Metrics from the specified time interval needs to be shown/calculated.

### How to reproduce

Collect DORA metrics from any datasource (I was testing my PagerDuty plugin), and specify a custom time-range.

See screenshot. I set it to 15 mins, but it goes all the way back to 22/06.
![image](https://user-images.githubusercontent.com/25063936/199674402-680b7459-8eb7-4830-8f5d-69a4bbc02416.png)

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hey @keon94 , there're a few cases here.

1. For time-series charts like `Number of Deployments`, I created a series of calendar months for the last six months and use it to join the actual data; if not, the month with no deployment will not be shown in the X-axis. In this case, the X-axis will always display the last six months, so the metrics does not honor time-range by design.
![image](https://user-images.githubusercontent.com/14050754/200510650-d7ef9eb9-7fc8-47cd-bdaa-5274f2b8c281.png)

   #### Improvements 
   Instead of adding time-range filter here, how about rename `Number of Deployments` to `Number of Deployments [Last six months]`?

2. For text charts like `Deployment Frequency`, the SQL takes the FROM date to create calendar dates to calculate if Deployment Frequency falls into `daily`, `weekly` or `monthly`. In this case, the deployments being calculated are filtered by the generated calendar dates.
![image](https://user-images.githubusercontent.com/14050754/200513614-194c5f28-1986-4d9d-9d09-739db313d18c.png)
   #### Improvements 
   Any suggestions? @keon94 

3. For text charts like `Lead Time for Changes`, `Median Time to Restore Service` and `Change Failure Rate`, the SQL takes the time-range.
![image](https://user-images.githubusercontent.com/14050754/200514397-406cc28d-42a6-495c-8fe3-afe15223afc6.png)
