### ISSUE TITLE
[Feature] The site is not responsive as per the screen size :https://devlake.apache.org/

### ISSUE THREAD

**Issue by UtkarshMishra12** [apache/incubator-devlake#3903]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

[Feature] The site is not responsive as per the screen size :https://devlake.apache.org/

https://user-images.githubusercontent.com/67385503/206720420-491182dd-6a6a-4ae4-9815-c9f22e910918.mp4

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Thanks for the report, looking forward to your PR. 😊

**Comment by miraz-mondal** [comment]
I would like to add more this issue is present in more pages. DORA and Engineering Overview page has the same issue. Need to work on Header and Footer height and weight! 
![res2](https://user-images.githubusercontent.com/89645073/210579945-38200239-7e07-41fd-9281-f3bbee8b280e.png)
![res1](https://user-images.githubusercontent.com/89645073/210579952-bf80449e-1974-4743-b8aa-a0435720592b.png)

**Comment by Startrekzky** [comment]
@miraz-mondal I just checked, and it is displayed properly on iPhone XR and other screens. I'll close the ticket for now.

![image](https://user-images.githubusercontent.com/14050754/216888995-1f780d27-8b37-4818-9058-c39a6715205d.png)
