### ISSUE TITLE
[Bug][Gitex] Unable to cancel gitextractor when preparing data 

### ISSUE THREAD

**Issue by warren830** [apache/incubator-devlake#4188]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When gitextractor is preparing data, we cannot cancel the pipeline because libgit2 does not support cancel

### What do you expect to happen

Even if gitextractor is preparing data, we should be able to cancel the whole pipeline

### How to reproduce

Use normal mode to collect more than 2 github/gitlab repos, and when the pipeline is running, click `cancel`

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
Maybe just leave `gitextractor` running, and ignore its output ?  Can we do like this?

**Comment by klesh** [comment]
> Maybe just leave `gitextractor` running, and ignore its output ? Can we do like this?

It is one way to go... however, It is not reliable, there is a chance that too many Git Clone operations are stuck in the background and eating out the system file descriptors.

I prefer the following options:
- Get rid of the `git2go` and use the `gogit` only which supports `context`. `git2go` has always been problematic since it depends on the `libgit2` C library. However, doing so would require a huge rewrite.
- Find a way for `git2go` to support cancellation, I found interesting discussion of the topic, it might be possible to add cancellation support for `git2go`
  - [git - libgit2 - clone operation with Github - Stack Overflow](https://stackoverflow.com/questions/25207194/libgit2-clone-operation-with-github)
  - [Error when cancel a Repository.Clone · Issue #780 · libgit2/libgit2sharp](https://github.com/libgit2/libgit2sharp/issues/780)

**Comment by d4x1** [comment]
I find `gogit` has been used when clone a repo. I don't know why don't choose it as default at the beginning. Are there some special reasons ?

By comparing the stars and activity(commit history) of `gogit` and `git2go` roughly, gogit is a better choice. I can help to rewrite this part if it not urgent.

**Comment by klesh** [comment]
@d4x1 `git2go` was chosen because it has more features and is faster than `gogit`.
I don't think it is urgent.  Feel free to do so, appreciated it ❤️

**Comment by d4x1** [comment]
> @d4x1 `git2go` was chosen because it has more features and is faster than `gogit`. I don't think it is urgent. Feel free to do so, appreciated it ❤️

I find a comment here, https://github.com/apache/incubator-devlake/blob/main/backend/plugins/gitextractor/parser/clone.go#L33

replacing git2go with gogit will lose some performance, is this acceptable ?

Before doing it, I think we should come to an agreement.

**Comment by klesh** [comment]
Well, it has been a while since we tested it.
Maybe we should do another round, there were two things that impacted the performance IIRC:

1. Iterates all commits
2. Calculates diff between 2 commits.

Can we write Benchmark PoC with those actions covered to test on a couple of medium size repositories, like `clickhouse` and `pingcap`. So we can assess how slow it will be in the real-world.

**Comment by klesh** [comment]
@d4x1 I want to express my gratitude for the confirmation - it is very thoughtful and much appreciated! ❤️

**Comment by d4x1** [comment]
> Well, it has been a while since we tested it. Maybe we should do another round, there were two things that impacted the performance IIRC:
> 
>     1. Iterates all commits
> 
>     2. Calculates diff between 2 commits.
> 
> 
> Can we write Benchmark PoC with those actions covered to test on a couple of medium size repositories, like `clickhouse` and `pingcap`. So we can assess how slow it will be in the real-world.

Benchmark is necessary. +1
But I am doubt about whether pingcat or clikckhouse is appropriate. Does devlake team has any statistics about the pct90 size of repos it will analyse?
I think this data varies greatly from scenario to scenario. But I have no idea on how to get a appropriate test repository.

**Comment by klesh** [comment]
> > Well, it has been a while since we tested it. Maybe we should do another round, there were two things that impacted the performance IIRC:
> > ```
> > 1. Iterates all commits
> > 
> > 2. Calculates diff between 2 commits.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can we write Benchmark PoC with those actions covered to test on a couple of medium size repositories, like `clickhouse` and `pingcap`. So we can assess how slow it will be in the real-world.
> 
> Benchmark is necessary. +1 But I am doubt about whether pingcap or clikckhouse is appropriate. Does devlake team has any statistics about the pct90 size of repos it will analyse? I think this data varies greatly from scenario to scenario. But I have no idea on how to get a appropriate test repository.

Nah, not really. There are not enough resources to conduct such a massive investigation and gitext has never been a bottleneck compared to other departments, such as collecting data from API, Chart loading speed, etc.

I would say randomly picking a couple of famous and long-lived open-source projects is sufficient at this point.

**Comment by d4x1** [comment]
Got it.

**Comment by d4x1** [comment]
I am still working on it and it will be updated.

**Comment by d4x1** [comment]
Keep this issue.

**Comment by stultus** [comment]
One of my blueprint is stuck at the gitextractor section for the past 5 days.  Is there any way to proceed to next step?

**Comment by klesh** [comment]
@stultus was it stuck at the clone stage? if that was true, the only solution for now is to restart the `devlake` container. 🥲
