### ISSUE TITLE
[Bug][UI] The "Tasks Completed" counter can exceed the total

### ISSUE THREAD

**Issue by keon94** [apache/incubator-devlake#4241]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Rerunning a task caused the counter to go over the total task count.

![image](https://user-images.githubusercontent.com/25063936/213611100-6ef0ccb3-137c-4d62-b94b-649c618bcf3f.png)

### What do you expect to happen

The counter should not exceed the total task count.

### How to reproduce

Pick any pipeline and run it. Then rerun any of its tasks, and this will happen. I tried Jenkins and Github.

### Anything else

I believe the correct behavior should be to only change the counter if a previously failed job succeeds (+1) or a previously successful job fails (-1). Otherwise, leave it alone.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@Startrekzky  please take a look at this

**Comment by Startrekzky** [comment]
@keon94 @klesh `Task Completed` is for users to understand if `all tasks of a pipeline have been successfully finished`, rather than the actual number of tasks being successfully run. According to this:
- The denominator should be the number of a pipeline's default tasks
- The numerator should be the successful tasks of a pipeline's default tasks (if rerunning a default task, the new task and its original copy should be considered as the same task)

For example, if a pipeline has 7 default tasks. Then the denominator should always be 7。
- If 2 tasks failed, then the task completed should be 5/7. When rerunning the 2 failed tasks and 1 succeeds, the number will be 6/7.
- If 7 tasks all passed, then the task completed should be 7/7. When rerunning 1 task and it succeeds, the number will still be 7/7.

I hope it makes sense.

**Comment by Startrekzky** [comment]
This is not urgent so I removed it from the milestone.
