### ISSUE TITLE
[Question][jira] Authentication failed on JIRA Server

### ISSUE THREAD

**Issue by shashank-bgp** [apache/incubator-devlake#4350]
I am trying to access the apache devlake UI, and encountering the error as shown in the image below:
![devlake](https://user-images.githubusercontent.com/57932092/217335755-a8cd3781-3b4c-4216-9c66-23e00310fd18.PNG)

When we click on test connection, it pops up as test failed! check your configuration. We need to put the certificate in the docker image, can anyone tell exactly at which location inside the docker image can we put the certificates?

Another issue is, if I have put the certificate at /usr/share/pki/ca-trust-source/anchors/ location in docker image, and committed the image, how can we use the newer version of the image tag in the devlake UI in the backend?

Please suggest any resolution on this.

**Comment by shashank-bgp** [comment]
I tried to create devlake from EKS too, but there is again authentication failure. Can someone suggest where to put the certificates, so that the access could be made in EKS too?

**Comment by mindlesscloud** [comment]
Your Endpoint URL doesn't look right, it should be `https://jira.regeneron.com/rest/`.
If you are sure it is caused by the shortage of certificates, please follow this [doc](https://devlake.apache.org/docs/next/Troubleshooting/Configuration#failed-to-collect-data-from-the-server-with-a-self-signed-certificate) to install your certificates
