### ISSUE TITLE
[Question][Grafana] Panel lead time for changes DORA

### ISSUE THREAD

**Issue by julianolsdominguesTW** [apache/incubator-devlake#4651]
## Question
Hey team, hope everything is ok!

We were making some checks in the lead time for changes DORA panel, and we noticed that the _clt table selects the minimum change_lead_time value (rank = 1) instead of the average of the month.
Are we missing something here? 
Thanks for your help!

## Screenshots
![image](https://user-images.githubusercontent.com/117674056/224835689-4c4700ae-c1ac-47df-b4f3-e800a4d10930.png)

**Comment by Startrekzky** [comment]
Hi @julianolsdominguesTW 
Good catch. It seems `_find_clt_rank_each_month`  and `_clt`  are two equivalent temp tables, we should get rid of one.

The idea of `_clt` is to get the median(not mean) change lead time for each month. Since MySQL doesn't support an aggregate function like median(), we have to first percent_rank() all records, and then find out the 50th percentile value (the value of the record with the biggest rank that <= 0.5).

I hope it answers your question.
