### ISSUE TITLE
[Feature][transformations] regex deployments by workflow runs name

### ISSUE THREAD

**Issue by Afig08** [apache/incubator-devlake#4825]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a DevOps engineer, I would love to have devlake track my workflow runs names for deployments instead of Job name

### Description

the reason I mention workflow runs its because most companies will likely have workflow runs specified by environment, Deploy-production or Deploy-Staging , Jobs names aren't necessarily unique. you can have deploy job name in both workflow runs. Ive seen the same job name in different workflow runs and that can make it difficult to sort through and determine what jobs is for Production and what job is for other environments.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
Thanks for the feature request, can @Startrekzky  take a look at it?

**Comment by klesh** [comment]
Make sense to me.   I would like to see some screenshots to help us understand intuitively.
@hezyin what do you think

**Comment by hezyin** [comment]
@klesh @Startrekzky Alejandro and I had a chat on this, and here's what he told me:

> One of his larger repos has GitHub workflows with names "Deploy-production" and "Deploy-staging". The jobs under those two workflows share the same names, like "deploy-api", "deploy-frontend", and etc. So DevLake's regexes on GitHub job names don't work very well for this repo.

**Comment by Startrekzky** [comment]
Got it. My suggestion for 
- long-term solution: move the `deployment` definition to the domain layer configuration. The same goes for `issue types` and `issue statuses`, `pr statuses`, `incidents`, etc. This provides an easier way for users to edit configuration in one setting page, rather than going to each project/bp to edit.
- short-term solution: support more entities and regex patterns when defining `deployment` in the bp transformation.

I prefer not to do the short-term solution but the long-term solution in the later versions like v0.19.

cc. @hezyin @klesh

**Comment by Startrekzky** [comment]
I think this issue has been solved along with the fixes for #4869 . DevLake has changed the definition of deployments from a GitHub job to a GitHub workflow run.

You can find the change in the latest v0.17 beta versions.
