### ISSUE TITLE
[Doc][Dashboard] Outdated links to Grafana doc

### ISSUE THREAD

**Issue by hezyin** [apache/incubator-devlake#4861]
The links to the Grafana doc are outdated in our dashboards, reported by a user in the Slack.

<img width="473" alt="Screen Shot 2023-04-04 at 7 29 38 PM" src="https://user-images.githubusercontent.com/2908155/229967186-53082d17-aee1-445c-9138-0c552576b945.png">

![image](https://user-images.githubusercontent.com/2908155/229967229-29b8ca71-4fe1-44af-93b4-4ed1b17b54f8.png)

**Comment by Hopeah** [comment]
@hezyin I checked main and release-v0.16 branches, those both have correctly updated links to Grafana doc (looks like it was done in this PR, https://github.com/apache/incubator-devlake/pull/4617). Since live version doesn't reflect this, could it be that these changes haven't been pushed to release yet?
